/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author patricia
 */
public class BeitragFrame extends javax.swing.JFrame {

    /**
     * Creates new form BeitragFrame
     */
    public BeitragFrame() {
        initComponents();
        displayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GruppenwahlPost = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        BeitragText = new javax.swing.JTextArea();
        PostenButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        PostTitel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        GruppenwahlPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GruppenwahlPostActionPerformed(evt);
            }
        });

        BeitragText.setColumns(20);
        BeitragText.setRows(5);
        BeitragText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BeitragTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(BeitragText);

        PostenButton.setText("Beitrag Posten");
        PostenButton.setEnabled(false);
        PostenButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PostenButtonStateChanged(evt);
            }
        });
        PostenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PostenButtonMouseClicked(evt);
            }
        });
        PostenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostenButtonActionPerformed(evt);
            }
        });

        CloseButton.setText("Close");
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseButtonMouseEntered(evt);
            }
        });
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        PostTitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostTitelActionPerformed(evt);
            }
        });
        PostTitel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PostTitelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(PostTitel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(GruppenwahlPost, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addComponent(PostenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CloseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostenButton)
                    .addComponent(GruppenwahlPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(PostTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PostenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostenButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed

    }//GEN-LAST:event_CloseButtonActionPerformed

    private void CloseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseButtonMouseEntered

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        dispose();
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void GruppenwahlPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GruppenwahlPostActionPerformed

    }//GEN-LAST:event_GruppenwahlPostActionPerformed

    private void PostTitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostTitelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostTitelActionPerformed

    private void BeitragTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BeitragTextKeyTyped
        PostenButton.setEnabled(true);
    }//GEN-LAST:event_BeitragTextKeyTyped

    private void PostTitelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PostTitelKeyTyped
        PostenButton.setEnabled(true);
    }//GEN-LAST:event_PostTitelKeyTyped

    private void PostenButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PostenButtonStateChanged
        if (BeitragText.getText().isEmpty() && PostTitel.getText().isEmpty()) {
            PostenButton.setEnabled(false);
        } else if (PostTitel.getText().isEmpty() && !BeitragText.getText().isEmpty()) {
            PostenButton.setEnabled(false);
        } else if (BeitragText.getText().isEmpty() && !PostTitel.getText().isEmpty()) {
            PostenButton.setEnabled(false);
        } else {
            PostenButton.setEnabled(true);
        }
    }//GEN-LAST:event_PostenButtonStateChanged

    private void PostenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostenButtonMouseClicked

        try {
            String Titel = PostTitel.getText();
            String Beitrag = BeitragText.getText();
            int MyID = Usercontroller.getInstance().getLoggedInUserId();
            String selectedGroup = GruppenwahlPost.getSelectedItem().toString();
            Club foundGroup = DB.getInstance().searchClubByName(selectedGroup);
            int ClubID = foundGroup.getId();
            DB.getInstance().addPost(Titel, Beitrag, MyID, ClubID);
            dispose();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_PostenButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeitragFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeitragFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeitragFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeitragFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeitragFrame().setVisible(true);
            }
        });
    }

    public void displayer() {
        try {
            int id = Usercontroller.getInstance().getLoggedInUserId();
            List<String> gruppe = DB.getInstance().getJoinedClubNames(id);
            GruppenwahlPost.removeAll();
            for (String e : gruppe) {
                GruppenwahlPost.addItem(e);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BeitragText;
    private javax.swing.JButton CloseButton;
    private javax.swing.JComboBox<String> GruppenwahlPost;
    private javax.swing.JTextField PostTitel;
    private javax.swing.JButton PostenButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
