package login;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author lisas
 */
public class ClubDetailsDialog extends JDialog {

    private Club club;

    /**
     * Creates new form CreateClubDialog
     *
     * @param club
     */
    public ClubDetailsDialog(Club club) {
        this.club = club;
        initComponents();
        jTextFieldClubName.setText(club.getName());
        jTextFieldDescription.setText(club.getDescription());
        jTextFieldImage.setText(club.getImage());
        jTextFieldMaxedSize.setText(String.valueOf(club.getSize()));
        getContentPane().setBackground(new java.awt.Color(169, 199, 199));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldClubName = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldImage = new javax.swing.JTextField();
        jTextClubName = new javax.swing.JTextField();
        jTextDescription = new javax.swing.JTextField();
        jTextImage = new javax.swing.JTextField();
        jTextMaxedSize = new javax.swing.JTextField();
        jTextFieldMaxedSize = new javax.swing.JTextField();
        jButtonShowMembers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(5, 81, 81));
        setModal(true);

        jTextFieldClubName.setEditable(false);
        jTextFieldClubName.setBackground(new java.awt.Color(203, 226, 226));
        jTextFieldClubName.setActionCommand("<Not Set>");

        jTextFieldDescription.setEditable(false);
        jTextFieldDescription.setBackground(new java.awt.Color(203, 226, 226));

        jTextFieldImage.setEditable(false);
        jTextFieldImage.setBackground(new java.awt.Color(203, 226, 226));

        jTextClubName.setEditable(false);
        jTextClubName.setBackground(new java.awt.Color(169, 199, 199));
        jTextClubName.setText("Gruppenname:");

        jTextDescription.setEditable(false);
        jTextDescription.setBackground(new java.awt.Color(169, 199, 199));
        jTextDescription.setText("Gruppenbeschreibung:");

        jTextImage.setEditable(false);
        jTextImage.setBackground(new java.awt.Color(169, 199, 199));
        jTextImage.setText("BildURL:");

        jTextMaxedSize.setEditable(false);
        jTextMaxedSize.setBackground(new java.awt.Color(169, 199, 199));
        jTextMaxedSize.setText("maximale Größe:");

        jTextFieldMaxedSize.setEditable(false);
        jTextFieldMaxedSize.setBackground(new java.awt.Color(203, 226, 226));

        jButtonShowMembers.setBackground(new java.awt.Color(0, 51, 51));
        jButtonShowMembers.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonShowMembers.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowMembers.setText("Mitglieder anzeigen lassen");
        jButtonShowMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonShowMembersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextMaxedSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextClubName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonShowMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jTextFieldClubName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMaxedSize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDescription))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextClubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMaxedSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaxedSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addComponent(jButtonShowMembers)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShowMembersMouseClicked
        if (club != null) {
            ClubMembersDialog clubMembersDialog = new ClubMembersDialog(club);
            clubMembersDialog.displayMembers();
            JDialog dialog = new JDialog(this, "Club Members", true); // Create a new JDialog
            dialog.getContentPane().add(clubMembersDialog); // Add the ClubMembersDialog panel to the JDialog's content pane
            dialog.setSize(451, 438); // Set the size of the JDialog 
            dialog.setLocationRelativeTo(this); // Set the location relative to the ClubDetailsDialog
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Keine Gruppe ausgewählt, bitte wähle eine Gruppe.");
        }
    }//GEN-LAST:event_jButtonShowMembersMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShowMembers;
    private javax.swing.JTextField jTextClubName;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTextField jTextFieldClubName;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldImage;
    private javax.swing.JTextField jTextFieldMaxedSize;
    private javax.swing.JTextField jTextImage;
    private javax.swing.JTextField jTextMaxedSize;
    // End of variables declaration//GEN-END:variables
}
