package login;

import javax.swing.DefaultListModel;
import java.util.List;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author lisas
 */
public class ClubMembersDialog extends javax.swing.JPanel {
    
    private DefaultListModel<String> listModel;
    private Club club;

    /**
     * Creates new form ClubMembersDialog
     *
     * @param club
     */
    public ClubMembersDialog(Club club) {
        this.club = club;

        initComponents();
        listModel = new DefaultListModel<>();
        jListMembers.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListMembers = new javax.swing.JList<>();

        jListMembers.setBackground(new java.awt.Color(169, 199, 199));
        jListMembers.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jListMembers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void displayMembers() {
        listModel.clear();
        List<String> members = Usercontroller.getInstance().getMembersNamesForClub(club);
        for (String member : members) {
            listModel.addElement(member);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListMembers;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
