package login;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author lisas
 */
public class ClubDetailsDialog extends JDialog {

    private Club club;
    /**
     * Creates new form CreateClubDialog
     */
    public ClubDetailsDialog(Club club) {
        this.club = club;
        initComponents();
        jTextClubName.setText(club.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldClubName = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldMemberSize = new javax.swing.JTextField();
        jTextFieldImage = new javax.swing.JTextField();
        jTextClubName = new javax.swing.JTextField();
        jTextDescription = new javax.swing.JTextField();
        jTextMemberSize = new javax.swing.JTextField();
        jTextImage = new javax.swing.JTextField();
        jTextMaxedSize = new javax.swing.JTextField();
        jTextFieldMaxedSize = new javax.swing.JTextField();
        jButtonShowMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(5, 81, 81));
        setModal(true);

        jTextFieldClubName.setEditable(false);
        jTextFieldClubName.setActionCommand("<Not Set>");
        jTextFieldClubName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldClubNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldClubNameFocusLost(evt);
            }
        });
        jTextFieldClubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClubNameActionPerformed(evt);
            }
        });

        jTextFieldDescription.setEditable(false);
        jTextFieldDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescriptionFocusLost(evt);
            }
        });

        jTextFieldMemberSize.setEditable(false);
        jTextFieldMemberSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMemberSizeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMemberSizeFocusLost(evt);
            }
        });

        jTextFieldImage.setEditable(false);
        jTextFieldImage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldImageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldImageFocusLost(evt);
            }
        });

        jTextClubName.setEditable(false);
        jTextClubName.setText("Gruppenname:");

        jTextDescription.setEditable(false);
        jTextDescription.setText("Gruppenbeschreibung:");

        jTextMemberSize.setEditable(false);
        jTextMemberSize.setText("Mitgliederanzahl:");

        jTextImage.setEditable(false);
        jTextImage.setText("BildURL:");
        jTextImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextImageActionPerformed(evt);
            }
        });

        jTextMaxedSize.setEditable(false);
        jTextMaxedSize.setText("maximale Größe:");
        jTextMaxedSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaxedSizeActionPerformed(evt);
            }
        });

        jTextFieldMaxedSize.setEditable(false);

        jButtonShowMember.setText("Mitglieder anzeigen lassen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextMemberSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaxedSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextClubName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonShowMember, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jTextFieldClubName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMemberSize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMaxedSize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDescription))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextClubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMemberSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMemberSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextMaxedSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaxedSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButtonShowMember)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldImageFocusLost
        if (jTextFieldImage.getText().isEmpty()) {
            jTextFieldImage.setText("URL für das Bild...");
        }
    }//GEN-LAST:event_jTextFieldImageFocusLost

    private void jTextFieldImageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldImageFocusGained
        if (jTextFieldImage.getText().equals("URL für das Bild...")) {
            jTextFieldImage.setText("");
        }
    }//GEN-LAST:event_jTextFieldImageFocusGained

    private void jTextFieldClubNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldClubNameFocusLost
       
    }//GEN-LAST:event_jTextFieldClubNameFocusLost

    private void jTextFieldClubNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldClubNameFocusGained
        if (jTextFieldClubName.getText().equals("Benenne deine Gruppe...")) {
            jTextFieldClubName.setText("");
        }
    }//GEN-LAST:event_jTextFieldClubNameFocusGained

    private void jTextFieldMemberSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMemberSizeFocusLost
        if (jTextFieldMemberSize.getText().isEmpty()) {
            jTextFieldMemberSize.setText("Maximale Gruppengröße?");
        }
    }//GEN-LAST:event_jTextFieldMemberSizeFocusLost

    private void jTextFieldMemberSizeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMemberSizeFocusGained
        if (jTextFieldMemberSize.getText().equals("Maximale Gruppengröße?")) {
            jTextFieldMemberSize.setText("");
        }
    }//GEN-LAST:event_jTextFieldMemberSizeFocusGained

    private void jTextFieldDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescriptionFocusLost
        if (jTextFieldDescription.getText().isEmpty()) {
            jTextFieldDescription.setText("Gib ihr eine Beschreibung...");
        }
    }//GEN-LAST:event_jTextFieldDescriptionFocusLost

    private void jTextFieldDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescriptionFocusGained
        if (jTextFieldDescription.getText().equals("Gib ihr eine Beschreibung...")) {
            jTextFieldDescription.setText("");
        }
    }//GEN-LAST:event_jTextFieldDescriptionFocusGained

    private void jTextFieldClubNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClubNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClubNameActionPerformed

    private void jTextImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextImageActionPerformed

    private void jTextMaxedSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaxedSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaxedSizeActionPerformed

    private void showClubDetails() {
         String clubName = "Gruppenname"; // Hier sollte der Name der Gruppe abgerufen werden
        String description = "Beschreibung der Gruppe"; // Hier sollte die Beschreibung der Gruppe abgerufen werden
        int clubSize = 10; // Hier sollte die Gruppengröße abgerufen werden
        String imageURL = "URL für das Bild";
        
        jTextFieldClubName.setText(clubName);
        jTextFieldDescription.setText(description);
        jTextFieldMemberSize.setText(String.valueOf(clubSize));
        jTextFieldImage.setText(imageURL);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShowMember;
    private javax.swing.JTextField jTextClubName;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTextField jTextFieldClubName;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldImage;
    private javax.swing.JTextField jTextFieldMaxedSize;
    private javax.swing.JTextField jTextFieldMemberSize;
    private javax.swing.JTextField jTextImage;
    private javax.swing.JTextField jTextMaxedSize;
    private javax.swing.JTextField jTextMemberSize;
    // End of variables declaration//GEN-END:variables
}
