package login;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author lisas
 */
public class CreateClubDialog extends JDialog {

    /**
     * Creates new form CreateClubDialog
     */
    public CreateClubDialog() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(169, 199, 199));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldClubName = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldClubSize = new javax.swing.JTextField();
        jTextFieldImage = new javax.swing.JTextField();
        jButtonCreateClub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(5, 81, 81));

        jTextFieldClubName.setBackground(new java.awt.Color(203, 226, 226));
        jTextFieldClubName.setText("Benenne deine Gruppe...");
        jTextFieldClubName.setActionCommand("<Not Set>");
        jTextFieldClubName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldClubNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldClubNameFocusLost(evt);
            }
        });

        jTextFieldDescription.setBackground(new java.awt.Color(203, 226, 226));
        jTextFieldDescription.setText("Gib ihr eine Beschreibung...");
        jTextFieldDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescriptionFocusLost(evt);
            }
        });

        jTextFieldClubSize.setBackground(new java.awt.Color(203, 226, 226));
        jTextFieldClubSize.setText("Maximale Gruppengröße?");
        jTextFieldClubSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldClubSizeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldClubSizeFocusLost(evt);
            }
        });

        jTextFieldImage.setBackground(new java.awt.Color(203, 226, 226));
        jTextFieldImage.setText("URL für das Bild...");
        jTextFieldImage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldImageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldImageFocusLost(evt);
            }
        });

        jButtonCreateClub.setBackground(new java.awt.Color(0, 51, 51));
        jButtonCreateClub.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonCreateClub.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateClub.setText("Gruppe erstellen");
        jButtonCreateClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateClubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jTextFieldClubName)
                    .addComponent(jTextFieldClubSize)
                    .addComponent(jTextFieldImage)
                    .addComponent(jButtonCreateClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextFieldClubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldClubSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCreateClub)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateClubActionPerformed
        boolean success = Usercontroller.getInstance().createClub(
                jTextFieldClubName.getText(),
                jTextFieldDescription.getText(),
                Integer.parseInt(jTextFieldClubSize.getText()),
                jTextFieldImage.getText()
        );

        if (success) {
            JOptionPane.showMessageDialog(CreateClubDialog.this, "Deine Gruppe wurde erfolgreich erstellt!");
            dispose(); // Schließt das Dialogfenster nach erfolgreichem Erstellen
        } else {
            JOptionPane.showMessageDialog(CreateClubDialog.this, "Fehler beim Erstellen deiner Gruppe.");
        }
    }//GEN-LAST:event_jButtonCreateClubActionPerformed

    private void jTextFieldClubNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldClubNameFocusLost
        if (jTextFieldClubName.getText().isEmpty()) {
            jTextFieldClubName.setText("Benenne deine Gruppe...");
        }
    }//GEN-LAST:event_jTextFieldClubNameFocusLost

    private void jTextFieldClubNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldClubNameFocusGained
        if (jTextFieldClubName.getText().equals("Benenne deine Gruppe...")) {
            jTextFieldClubName.setText("");
        }
    }//GEN-LAST:event_jTextFieldClubNameFocusGained

    private void jTextFieldDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescriptionFocusLost
        if (jTextFieldDescription.getText().isEmpty()) {
            jTextFieldDescription.setText("Gib ihr eine Beschreibung...");
        }
    }//GEN-LAST:event_jTextFieldDescriptionFocusLost

    private void jTextFieldDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescriptionFocusGained
        if (jTextFieldDescription.getText().equals("Gib ihr eine Beschreibung...")) {
            jTextFieldDescription.setText("");
        }
    }//GEN-LAST:event_jTextFieldDescriptionFocusGained

    private void jTextFieldClubSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldClubSizeFocusLost
        if (jTextFieldClubSize.getText().isEmpty()) {
            jTextFieldClubSize.setText("Maximale Gruppengröße?");
        }
    }//GEN-LAST:event_jTextFieldClubSizeFocusLost

    private void jTextFieldClubSizeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldClubSizeFocusGained
        if (jTextFieldClubSize.getText().equals("Maximale Gruppengröße?")) {
            jTextFieldClubSize.setText("");
        }
    }//GEN-LAST:event_jTextFieldClubSizeFocusGained

    private void jTextFieldImageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldImageFocusGained
        if (jTextFieldImage.getText().equals("URL für das Bild...")) {
            jTextFieldImage.setText("");
        }
    }//GEN-LAST:event_jTextFieldImageFocusGained

    private void jTextFieldImageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldImageFocusLost
        if (jTextFieldImage.getText().isEmpty()) {
            jTextFieldImage.setText("URL für das Bild...");
        }
    }//GEN-LAST:event_jTextFieldImageFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateClub;
    private javax.swing.JTextField jTextFieldClubName;
    private javax.swing.JTextField jTextFieldClubSize;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldImage;
    // End of variables declaration//GEN-END:variables
}
