package login;

/**
 *
 * @author lisas
 * freunde ausählen können aus freundeliste
 * was passiert wenn man auf freunde klickt? Software sagen wer meine Freunde sind
 * -> 1. add Freunde macht dialog auf, mit liste aller user (bis auf alle, die bereits meine freunde sind & man selbst)
 * 2. alle Freunde die man bereits geaddet hat
 * danach erst um feed kümmern
 * im panelFreind wird suchfeld benötigt (Textfeld)
 * provisorisch einen weiteren button "button", sobald man tippt & er sucht zu schwierig
 * klicken auf suchen => dann erst, funktioniert mit präfix FR -> Franziska (soll merken neuer Buchstaben &
 * direkt suchen noch zu schwierig)
 */
public class Homepage extends javax.swing.JFrame {
    
    public Homepage() {
        initComponents();
    }

    public void setLoggedInUsername(String username) {
        jLabelUsername.setText( username );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeadline = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelLeftHeadliner = new javax.swing.JLabel();
        jPanelAll = new javax.swing.JPanel();
        jLabelRightHeadliner = new javax.swing.JLabel();
        jPanelFeed = new javax.swing.JPanel();
        jButtonProfile = new javax.swing.JButton();
        jButtonFeed = new javax.swing.JButton();
        jButtonGroups = new javax.swing.JButton();
        jButtonFriends = new javax.swing.JButton();
        jPanelBelowToolBar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHeadline.setFont(new java.awt.Font("Papyrus", 0, 48)); // NOI18N
        jLabelHeadline.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeadline.setText("PLATON");
        getContentPane().add(jLabelHeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabelUsername.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setFont(new java.awt.Font("Krungthep", 0, 24)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Name");
        getContentPane().add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 113, 30));

        jLabelLeftHeadliner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Bilder/startseiteLeiste.JPEG"))); // NOI18N
        jLabelLeftHeadliner.setText("jLabel2");
        getContentPane().add(jLabelLeftHeadliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, -1));

        jPanelAll.setBackground(new java.awt.Color(169, 199, 199));

        jLabelRightHeadliner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Bilder/startseiteLeiste.JPEG"))); // NOI18N
        jLabelRightHeadliner.setText("jLabel3");

        jPanelFeed.setBackground(new java.awt.Color(37, 81, 81));

        jButtonProfile.setBackground(new java.awt.Color(148, 186, 186));
        jButtonProfile.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jButtonProfile.setText("Profil");

        jButtonFeed.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jButtonFeed.setForeground(new java.awt.Color(0, 102, 102));
        jButtonFeed.setText("Feed");
        jButtonFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeedActionPerformed(evt);
            }
        });

        jButtonGroups.setBackground(new java.awt.Color(156, 193, 193));
        jButtonGroups.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jButtonGroups.setText("Gruppen");
        jButtonGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupsActionPerformed(evt);
            }
        });

        jButtonFriends.setBackground(new java.awt.Color(165, 200, 200));
        jButtonFriends.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jButtonFriends.setText("Freunde");
        jButtonFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFeedLayout = new javax.swing.GroupLayout(jPanelFeed);
        jPanelFeed.setLayout(jPanelFeedLayout);
        jPanelFeedLayout.setHorizontalGroup(
            jPanelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jButtonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFeed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanelFeedLayout.setVerticalGroup(
            jPanelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFriends)
                    .addComponent(jButtonGroups)
                    .addComponent(jButtonFeed)
                    .addComponent(jButtonProfile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBelowToolBar.setOpaque(false);

        javax.swing.GroupLayout jPanelAllLayout = new javax.swing.GroupLayout(jPanelAll);
        jPanelAll.setLayout(jPanelAllLayout);
        jPanelAllLayout.setHorizontalGroup(
            jPanelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelAllLayout.createSequentialGroup()
                .addGroup(jPanelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAllLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabelRightHeadliner))
                    .addGroup(jPanelAllLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanelBelowToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAllLayout.setVerticalGroup(
            jPanelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelRightHeadliner)
                .addGap(5, 5, 5)
                .addComponent(jPanelFeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelBelowToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeedActionPerformed
        
    }//GEN-LAST:event_jButtonFeedActionPerformed

    private void jButtonGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupsActionPerformed
        
    }//GEN-LAST:event_jButtonGroupsActionPerformed

    private void jButtonFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFriendsActionPerformed
        jPanelBelowToolBar.removeAll();
        jPanelBelowToolBar.add(new PanelFriends());
        pack();
    }//GEN-LAST:event_jButtonFriendsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Homepage homepage = new Homepage();
                new Loginform(homepage).setVisible(true);
                if (Usercontroller.getInstance().getLoggedInUser() != null) {
                    homepage.setLoggedInUsername(Usercontroller.getInstance().getLoggedInUser().getUsername());
                    homepage.setVisible(true);
                }else{
                    System.exit(0);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFeed;
    private javax.swing.JButton jButtonFriends;
    private javax.swing.JButton jButtonGroups;
    private javax.swing.JButton jButtonProfile;
    private javax.swing.JLabel jLabelHeadline;
    private javax.swing.JLabel jLabelLeftHeadliner;
    private javax.swing.JLabel jLabelRightHeadliner;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelAll;
    private javax.swing.JPanel jPanelBelowToolBar;
    private javax.swing.JPanel jPanelFeed;
    // End of variables declaration//GEN-END:variables
}
