/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import java.util.LinkedList;
import java.util.List;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import login.Post;

/**
 * PanelFeed class represents a JPanel used for displaying a feed of posts.
 * Users can view posts from different groups or view all posts from the groups
 * they joined. It includes options to create a new post, like or dislike a
 * post, and refresh the feed. The feed is displayed in a JList, and users can
 * interact with posts using buttons. The class manages the interaction with the
 * database to retrieve and display posts.
 *
 * @author Antonia Buchsenschutz,Lisa Szelag,Patricia Warmulla,Kim Solveigh
 * Knutzen,Dominik Marlin Erhardt
 */
public class PanelFeed extends javax.swing.JPanel {

    private DefaultListModel<String> listModel;
    private List<Post> posts;

    /**
     * Creates new form PanelFeed
     */
    public PanelFeed(Homepage aThis) {
        initComponents();
        listModel = new DefaultListModel<>();
        PostAnzeige.setModel(listModel);
        posts = new LinkedList<Post>();
        displayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BeitragButton = new javax.swing.JButton();
        Groupchoice = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        PostAnzeige = new javax.swing.JList<>();
        DislikeButton = new javax.swing.JButton();
        LikeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(2, 70, 70));
        setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 500));

        BeitragButton.setBackground(new java.awt.Color(0, 51, 51));
        BeitragButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        BeitragButton.setForeground(new java.awt.Color(255, 255, 255));
        BeitragButton.setText("neuen Beitrag erstellen");
        BeitragButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BeitragButtonMouseClicked(evt);
            }
        });
        BeitragButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeitragButtonActionPerformed(evt);
            }
        });

        Groupchoice.setBackground(new java.awt.Color(169, 199, 199));
        Groupchoice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Groupchoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupchoiceActionPerformed(evt);
            }
        });

        PostAnzeige.setBackground(new java.awt.Color(169, 199, 199));
        PostAnzeige.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PostAnzeige.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(PostAnzeige);

        DislikeButton.setBackground(new java.awt.Color(0, 51, 51));
        DislikeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        DislikeButton.setForeground(new java.awt.Color(255, 255, 255));
        DislikeButton.setText("Dislike");
        DislikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DislikeButtonMouseClicked(evt);
            }
        });

        LikeButton.setBackground(new java.awt.Color(0, 51, 51));
        LikeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LikeButton.setForeground(new java.awt.Color(255, 255, 255));
        LikeButton.setText("Like");
        LikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LikeButtonMouseClicked(evt);
            }
        });
        LikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LikeButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LikeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DislikeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Groupchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BeitragButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Groupchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(BeitragButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DislikeButton)
                    .addComponent(LikeButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BeitragButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeitragButtonActionPerformed

    }//GEN-LAST:event_BeitragButtonActionPerformed
    /**
     * Handles the mouse click event for creating a new post. Instantiates a new
     * PostFrame, making it visible for the user to create a new post.
     *
     * @param evt The MouseEvent associated with the mouse click.
     */
    private void BeitragButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BeitragButtonMouseClicked
        PostFrame bf = new PostFrame();
        bf.setVisible(true);
    }//GEN-LAST:event_BeitragButtonMouseClicked
    /**
     * Handles the action event when the selection in the Groupchoice combobox
     * changes. Refreshes the feed display based on the selected group or shows
     * posts from all groups.
     *
     * @param evt The ActionEvent associated with the combobox selection change.
     */
    private void GroupchoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupchoiceActionPerformed

        feeddisplay();
    }//GEN-LAST:event_GroupchoiceActionPerformed

    private void LikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikeButtonActionPerformed

    }//GEN-LAST:event_LikeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Handles the mouse click event for the refresh button. Invokes the
     * {feeddisplay()} method to refresh the display of posts in the PostAnzeige
     * list based on the selected group in Gruppenwahl.
     *
     * @param evt The MouseEvent associated with the mouse click.
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        feeddisplay();
    }//GEN-LAST:event_jButton1MouseClicked
    /**
     * Handles the mouse click event for the likeButton. If a post is selected
     * in the PostAnzeige list, retrieves the corresponding post ID and updates
     * the like count in the database using the { DB likecounter(int, String)}
     * method with the counter type "LIKE_COUNT". After updating the dislike
     * count, refreshes the feed display by calling the {feeddisplay()} method.
     *
     * @param evt The MouseEvent associated with the mouse click.
     */
    private void LikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LikeButtonMouseClicked
        try {
            if (PostAnzeige.getSelectedIndex() >= 0) {
                int id = posts.get(PostAnzeige.getSelectedIndex()).getPostID();
                DB.getInstance().likecounter(id, "LIKE_COUNT");
                feeddisplay();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_LikeButtonMouseClicked
    /**
     * Handles the mouse click event for the DislikeButton. If a post is
     * selected in the PostAnzeige list, retrieves the corresponding post ID and
     * updates the dislike count in the database using the { DB likecounter(int,
     * String)} method with the counter type "DISLIKE_COUNT". After updating the
     * dislike count, refreshes the feed display by calling the {feeddisplay()}
     * method.
     *
     * @param evt The MouseEvent associated with the mouse click.
     */
    private void DislikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DislikeButtonMouseClicked
        try {
            if (PostAnzeige.getSelectedIndex() >= 0) {
                int id = posts.get(PostAnzeige.getSelectedIndex()).getPostID();
                DB.getInstance().likecounter(id, "DISLIKE_COUNT");
                feeddisplay();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DislikeButtonMouseClicked
    /**
     * Displays the feed based on the selected group in the Gruppenwahl combo
     * box.
     */
    public void feeddisplay() {
        try {
            listModel.clear();
            if (Groupchoice.getItemCount() > 0) {
                if (Groupchoice.getSelectedItem().toString().equals("alle")) {
                    this.posts.clear();
                    int id = Usercontroller.getInstance().getLoggedInUserId();
                    List<Club> gruppe = DB.getInstance().getClubsForUser(id);
                    List<Integer> clubIDs = new LinkedList<>();
                    for (Club c : gruppe) {
                        clubIDs.add(c.getId());
                    }
                    for (int i : clubIDs) {
                        this.posts.addAll(DB.getInstance().readPost("CLUBID", i));
                    }
                } else {
                    String selectedGroup = Groupchoice.getSelectedItem().toString();
                    Club foundGroup = DB.getInstance().searchClubByName(selectedGroup);
                    int ClubID = foundGroup.getId();
                    this.posts = DB.getInstance().readPost("CLUBID", ClubID);
                }
                for (Post p : posts) {
                    List<Integer> userid = new LinkedList<>();
                    userid.add(p.getUserID());
                    List<String> username = DB.getInstance().nameIdSearch(userid);
                    String post = String.format("von %s am %s | %s | %s | Like: %d Dislike: %d ",
                            username.get(0), p.getDate(), p.getTitel(), p.getDescription(), p.getLikecount(), p.getDislikecount());
                    listModel.addElement(post);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * Updates and displays the content of the GroupChoice combo box. Retrieves
     * the list of groups that the logged-in user has joined and populates the
     * combo box with these group names. Also adds an option to view posts from
     * all groups. Finally, calls the feeddisplay() method to refresh and
     * display the feed based on the selected group.
     *
     * @throws SQLException if there is an error accessing the database.
     */
    public void displayer() {
        try {
            int id = Usercontroller.getInstance().getLoggedInUserId();
            List<String> gruppe = DB.getInstance().getJoinedClubNames(id);
            Groupchoice.removeAll();
            for (String e : gruppe) {
                Groupchoice.addItem(e);
            }
            Groupchoice.addItem("alle");
            feeddisplay();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeitragButton;
    private javax.swing.JButton DislikeButton;
    private javax.swing.JComboBox<String> Groupchoice;
    private javax.swing.JButton LikeButton;
    private javax.swing.JList<String> PostAnzeige;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
