package login;

import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author lisas //Gruppe löschen & Freunde hinzufügen
 */
public class PanelClubs extends javax.swing.JPanel {
    
    private DefaultListModel<String> listModel;
    public List<Club> result;
    public String tmpClubname;
    

    public PanelClubs(Homepage aThis) {
        /*
        listModel = new DefaultListModel<>();
        jListJoinedClubs.setModel(listModel);
        displayClubs();
        */
        initComponents();
        jButtonLeaveClub.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCreateClub = new javax.swing.JButton();
        jListJoinedClubs = new java.awt.List();
        jButtonJoinNewClub = new javax.swing.JButton();
        jButtonLeaveClub = new javax.swing.JButton();
        jTextFieldSearchBar = new java.awt.TextField();
        jListSearchFriends = new java.awt.List();

        setBackground(new java.awt.Color(5, 81, 81));

        jButtonCreateClub.setText("Gruppe erstellen");
        jButtonCreateClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateClubActionPerformed(evt);
            }
        });

        jListJoinedClubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListJoinedClubsMouseClicked(evt);
            }
        });

        jButtonJoinNewClub.setText("neuer Gruppe beitreten");
        jButtonJoinNewClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinNewClubActionPerformed(evt);
            }
        });

        jButtonLeaveClub.setText("aus Gruppe austreten");
        jButtonLeaveClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveClubActionPerformed(evt);
            }
        });

        jTextFieldSearchBar.setText("Suche...");
        jTextFieldSearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSearchBarMouseClicked(evt);
            }
        });
        jTextFieldSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchBarActionPerformed(evt);
            }
        });

        jListSearchFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSearchFriendsMouseClicked(evt);
            }
        });
        jListSearchFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListSearchFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jListJoinedClubs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateClub, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonJoinNewClub)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLeaveClub, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jTextFieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(185, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jListSearchFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(185, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateClub)
                    .addComponent(jButtonJoinNewClub)
                    .addComponent(jButtonLeaveClub))
                .addGap(199, 199, 199)
                .addComponent(jListJoinedClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(jTextFieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(199, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jListSearchFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJoinNewClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinNewClubActionPerformed
        
    }//GEN-LAST:event_jButtonJoinNewClubActionPerformed

    private void jButtonCreateClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateClubActionPerformed
        CreateClubDialog createClubDialog = new CreateClubDialog();
        createClubDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateClubActionPerformed

    private void jButtonLeaveClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveClubActionPerformed
    

    }//GEN-LAST:event_jButtonLeaveClubActionPerformed

    private void jListJoinedClubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListJoinedClubsMouseClicked
        /*int selectedClubIndex = jListJoinedClubs.getSelectedIndex();
        
        if (selectedClubIndex >= 0) {
            jButtonLeaveClub.setEnabled(true);
            Club selectedClub = getSelectedClub(); //AUS DATENBANK
            
            if (selectedClub != null) {
                boolean success = DB.removeMemberFromGroup(selectedClub.getId());
                if (success) {
                    JOptionPane.showMessageDialog(this, "Du hast die Gruppe verlassen.");
                    displayClubs();
                } else {
                    JOptionPane.showMessageDialog(this, "Fehler beim Verlassen der Gruppe.");
                }
            }
        } else {
            jButtonLeaveClub.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Bitte wähle eine Gruppe aus, um sie zu verlassen.");
        }
    */
    }//GEN-LAST:event_jListJoinedClubsMouseClicked

    private void jTextFieldSearchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarMouseClicked
        jTextFieldSearchBar.setText("");
    }//GEN-LAST:event_jTextFieldSearchBarMouseClicked

    private void jTextFieldSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarActionPerformed

        String searchText = jTextFieldSearchBar.getText();
        List<Club> searchResult = Usercontroller.getInstance().searchClub(searchText);
        result = searchResult;
        jListSearchFriends.removeAll();
        for (Club e : searchResult) {
            jListSearchFriends.add(e.getClub_name());
        }
    }//GEN-LAST:event_jTextFieldSearchBarActionPerformed

    private void jListSearchFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSearchFriendsMouseClicked
        List<Club> tmp = this.result;
        int x = jListSearchFriends.getSelectedIndex();
        if (x >= 0) {
            //jButtonAddFriend.setEnabled(true);
            System.out.println(x);
            tmpClubname = tmp.get(x).getClub_name();
        }
    }//GEN-LAST:event_jListSearchFriendsMouseClicked

    private void jListSearchFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListSearchFriendsActionPerformed
        //TODO
    }//GEN-LAST:event_jListSearchFriendsActionPerformed
/*
    private void displayClubs() {
        listModel.clear();
        List<String> ids = Usercontroller.getInstance().getClubs();
        for (String e : ids) {
            listModel.addElement(e);
        }
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateClub;
    private javax.swing.JButton jButtonJoinNewClub;
    private javax.swing.JButton jButtonLeaveClub;
    private java.awt.List jListJoinedClubs;
    private java.awt.List jListSearchFriends;
    private java.awt.TextField jTextFieldSearchBar;
    // End of variables declaration//GEN-END:variables
}
