/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

/**
 *
 * @author patricia
 */
public class PanelProfile extends javax.swing.JPanel {

    /**
     * Creates new form PanelProfile
     * @param aThis
     */
    public PanelProfile(Homepage aThis) {
        initComponents();
        display_data();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSaveProfile = new javax.swing.JButton();
        jButtonProfilePicture = new javax.swing.JLabel();
        jTextFielfName = new javax.swing.JTextField();
        JTextFieldUsername = new javax.swing.JTextField();
        jTextFieldLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListHobbies = new javax.swing.JList<>();
        jTextFieldDescription = new javax.swing.JTextField();
        jButtonChangeProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(6, 81, 81));

        jButtonSaveProfile.setText("speichern");

        jButtonProfilePicture.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProfilePicture.setText("BILD");
        jButtonProfilePicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 9, true));

        jTextFielfName.setText("Name");
        jTextFielfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielfNameActionPerformed(evt);
            }
        });

        JTextFieldUsername.setText("Username");
        JTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldUsernameActionPerformed(evt);
            }
        });

        jTextFieldLocation.setText("Standort");
        jTextFieldLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLocationActionPerformed(evt);
            }
        });

        jListHobbies.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListHobbies.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListHobbiesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListHobbies);

        jTextFieldDescription.setText("Beschreibung");
        jTextFieldDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescriptionActionPerformed(evt);
            }
        });

        jButtonChangeProfile.setText("bearbeiten");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonChangeProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaveProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextFieldUsername)
                            .addComponent(jTextFieldLocation)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextFieldDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jTextFielfName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButtonSaveProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonChangeProfile))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTextFielfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(JTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void display_data() {
       jTextFielfName.setText(Usercontroller.getInstance().getLoggedInUser().getName());
       JTextFieldUsername.setText(Usercontroller.getInstance().getLoggedInUser().getUsername());
       jTextFieldLocation.setText(Usercontroller.getInstance().getLoggedInUser().standort());
       jTextFieldDescription.setText(Usercontroller.getInstance().getLoggedInUser().beschreibung());
    }
    
    private void jTextFielfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielfNameActionPerformed

    }//GEN-LAST:event_jTextFielfNameActionPerformed

    private void JTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldUsernameActionPerformed
        
    }//GEN-LAST:event_JTextFieldUsernameActionPerformed

    private void jTextFieldLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLocationActionPerformed

    }//GEN-LAST:event_jTextFieldLocationActionPerformed

    private void jTextFieldDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescriptionActionPerformed

    }//GEN-LAST:event_jTextFieldDescriptionActionPerformed

    private void jListHobbiesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListHobbiesValueChanged

    }//GEN-LAST:event_jListHobbiesValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldUsername;
    private javax.swing.JButton jButtonChangeProfile;
    private javax.swing.JLabel jButtonProfilePicture;
    private javax.swing.JButton jButtonSaveProfile;
    private javax.swing.JList<String> jListHobbies;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFielfName;
    // End of variables declaration//GEN-END:variables
}
