/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author lisas
 */
public class PanelFriends extends javax.swing.JPanel {

    private DefaultListModel<String> listModel;
    public List<User> result;
    public String tmpUsername;

    /**
     * Creates new form PanelFriends
     */
    public PanelFriends(Homepage aThis) {
        initComponents();
        listModel = new DefaultListModel<>();
        jListFriends.setModel(listModel);
        displayFriends();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFriendsBackground = new javax.swing.JPanel();
        jButtonAddFriend = new javax.swing.JButton();
        jTextFieldSearchBar = new java.awt.TextField();
        jListSearchFriends = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFriends = new javax.swing.JList<>();

        setOpaque(false);

        jPanelFriendsBackground.setBackground(new java.awt.Color(5, 81, 81));

        jButtonAddFriend.setText("add Friend");
        jButtonAddFriend.setEnabled(false);
        jButtonAddFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddFriendMouseClicked(evt);
            }
        });
        jButtonAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFriendActionPerformed(evt);
            }
        });

        jTextFieldSearchBar.setText("Suche...");
        jTextFieldSearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSearchBarMouseClicked(evt);
            }
        });
        jTextFieldSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchBarActionPerformed(evt);
            }
        });

        jListSearchFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSearchFriendsMouseClicked(evt);
            }
        });
        jListSearchFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListSearchFriendsActionPerformed(evt);
            }
        });

        jListFriends.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListFriends);

        javax.swing.GroupLayout jPanelFriendsBackgroundLayout = new javax.swing.GroupLayout(jPanelFriendsBackground);
        jPanelFriendsBackground.setLayout(jPanelFriendsBackgroundLayout);
        jPanelFriendsBackgroundLayout.setHorizontalGroup(
            jPanelFriendsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFriendsBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelFriendsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFriendsBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFriendsBackgroundLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jListSearchFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddFriend)
                .addGap(14, 14, 14))
        );
        jPanelFriendsBackgroundLayout.setVerticalGroup(
            jPanelFriendsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFriendsBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelFriendsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFriendsBackgroundLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButtonAddFriend))
                    .addGroup(jPanelFriendsBackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFriendsBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jListSearchFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFriendsBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFriendsBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFriendActionPerformed
        Usercontroller.getInstance().addFriends(tmpUsername);
        displayFriends();
        System.out.println("Freund hinzugefügt.");
    }//GEN-LAST:event_jButtonAddFriendActionPerformed

    private void jTextFieldSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarActionPerformed

        String searchText = jTextFieldSearchBar.getText();
        List<User> searchResult = Usercontroller.getInstance().searchForUser(searchText);
        result = searchResult;
        jListSearchFriends.removeAll();
        for (User e : searchResult) {
            jListSearchFriends.add(e.getUsername());
        }
    }//GEN-LAST:event_jTextFieldSearchBarActionPerformed

    private void jListSearchFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListSearchFriendsActionPerformed
        //TODO
    }//GEN-LAST:event_jListSearchFriendsActionPerformed

    private void jTextFieldSearchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarMouseClicked
        jTextFieldSearchBar.setText("");
    }//GEN-LAST:event_jTextFieldSearchBarMouseClicked

    private void jButtonAddFriendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddFriendMouseClicked

    }//GEN-LAST:event_jButtonAddFriendMouseClicked

    private void jListSearchFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSearchFriendsMouseClicked
        List<User> tmp = this.result;
        int x = jListSearchFriends.getSelectedIndex();
        if (x >= 0) {
            jButtonAddFriend.setEnabled(true);
            System.out.println(x);
            tmpUsername = tmp.get(x).getUsername();
        }
    }//GEN-LAST:event_jListSearchFriendsMouseClicked

    private void displayFriends() {
        listModel.clear();
        List<String> ids = Usercontroller.getInstance().getFriends();
        for (String e : ids) {
            listModel.addElement(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddFriend;
    private javax.swing.JList<String> jListFriends;
    private java.awt.List jListSearchFriends;
    private javax.swing.JPanel jPanelFriendsBackground;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField jTextFieldSearchBar;
    // End of variables declaration//GEN-END:variables
}
