/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.sql.SQLException;
import java.util.List;
import login.PanelFeed;

/**
 *
 * @author patricia
 */
public class PostFrame extends javax.swing.JFrame {

    /**
     * Creates new form PostFrame
     */
    public PostFrame() {
        initComponents();
        displayer();
        getContentPane().setBackground(new java.awt.Color(169, 199, 199));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupChoicePost = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        PostText = new javax.swing.JTextArea();
        PostenButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        PostTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        GroupChoicePost.setBackground(new java.awt.Color(203, 226, 226));
        GroupChoicePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupChoicePostActionPerformed(evt);
            }
        });

        PostText.setBackground(new java.awt.Color(203, 226, 226));
        PostText.setColumns(20);
        PostText.setRows(5);
        PostText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PostTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(PostText);

        PostenButton.setBackground(new java.awt.Color(0, 51, 51));
        PostenButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        PostenButton.setForeground(new java.awt.Color(255, 255, 255));
        PostenButton.setText("Beitrag Posten");
        PostenButton.setEnabled(false);
        PostenButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PostenButtonStateChanged(evt);
            }
        });
        PostenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PostenButtonMouseClicked(evt);
            }
        });
        PostenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostenButtonActionPerformed(evt);
            }
        });

        CloseButton.setBackground(new java.awt.Color(0, 51, 51));
        CloseButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 255, 255));
        CloseButton.setText("Close");
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseButtonMouseEntered(evt);
            }
        });
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        PostTitle.setBackground(new java.awt.Color(203, 226, 226));
        PostTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostTitleActionPerformed(evt);
            }
        });
        PostTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PostTitleKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(GroupChoicePost, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                            .addComponent(PostenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PostTitle)
                        .addComponent(jScrollPane1))
                    .addComponent(CloseButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CloseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostenButton)
                    .addComponent(GroupChoicePost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(PostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PostenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostenButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed

    }//GEN-LAST:event_CloseButtonActionPerformed

    private void CloseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseButtonMouseEntered

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        dispose();
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void GroupChoicePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupChoicePostActionPerformed

    }//GEN-LAST:event_GroupChoicePostActionPerformed

    private void PostTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostTitleActionPerformed

    private void PostTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PostTextKeyTyped
        PostenButton.setEnabled(true);
    }//GEN-LAST:event_PostTextKeyTyped

    private void PostTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PostTitleKeyTyped
        PostenButton.setEnabled(true);
    }//GEN-LAST:event_PostTitleKeyTyped

    private void PostenButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PostenButtonStateChanged
        if (PostText.getText().isEmpty() && PostTitle.getText().isEmpty()) {
            PostenButton.setEnabled(false);
        } else if (PostTitle.getText().isEmpty() && !PostText.getText().isEmpty()) {
            PostenButton.setEnabled(false);
        } else if (PostText.getText().isEmpty() && !PostTitle.getText().isEmpty()) {
            PostenButton.setEnabled(false);
        } else {
            PostenButton.setEnabled(true);
        }
    }//GEN-LAST:event_PostenButtonStateChanged

    private void PostenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostenButtonMouseClicked

        try {
            String Title = PostTitle.getText();
            String Beitrag = PostText.getText();  // Beitrag zu Post umbennenen??
            int MyID = Usercontroller.getInstance().getLoggedInUserId();
            String selectedGroup = GroupChoicePost.getSelectedItem().toString();
            Club foundGroup = DB.getInstance().searchClubByName(selectedGroup);
            int ClubID = foundGroup.getId();
            DB.getInstance().addPost(Title, Beitrag, MyID, ClubID);
            dispose();
            
            
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_PostenButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostFrame().setVisible(true);
            }
        });
    }

    public void displayer() {
        try {
            int id = Usercontroller.getInstance().getLoggedInUserId();
            List<String> group = DB.getInstance().getJoinedClubNames(id);
            GroupChoicePost.removeAll();
            for (String e : group) {
                GroupChoicePost.addItem(e);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JComboBox<String> GroupChoicePost;
    private javax.swing.JTextArea PostText;
    private javax.swing.JTextField PostTitle;
    private javax.swing.JButton PostenButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
